"""Replace the dashboard's Google Fonts requests with self-hosted files.

The dashboard is a built Vite app whose index.html links two Google stylesheets:
Inter for text and Material Symbols Outlined for icons. Those are third-party
requests that leak visitor IPs, block first paint, and stop the dashboard from
working offline. This downloads a latin subset of Inter and a Material Symbols
subset containing only the icon ligatures the app actually uses, writes them
into dashboard/assets/fonts/, and rewrites index.html to point at them.

Icon names are scraped from the built bundle, so adding an icon to the app and
rebuilding picks it up automatically.

Usage:  python tools/localise_dashboard_fonts.py [dashboard_dir]
"""
import os
import re
import sys
import urllib.request

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36")


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        return r.read()


def icon_names(dashboard: str) -> list:
    """Every Material Symbols ligature referenced by the built bundle."""
    names = set()
    assets = os.path.join(dashboard, "assets")
    for fn in os.listdir(assets):
        if not fn.endswith((".js", ".css")):
            continue
        src = open(os.path.join(assets, fn), encoding="utf-8", errors="ignore").read()
        # icon: `name` entries in nav/config objects
        names.update(re.findall(r"icon:\s*[`\"']([a-z][a-z0-9_]{2,})[`\"']", src))
        # children: `name` on a material-symbols span, including ternary branches
        for chunk in re.findall(r"material-symbols-outlined[^}]{0,200}", src):
            names.update(re.findall(r"[`\"']([a-z][a-z0-9_]{2,})[`\"']", chunk))
    # Drop tokens that are plainly Tailwind classes or code, not icon ligatures
    noise = {"div", "span", "children", "class", "classname", "text", "flex", "items",
             "center", "gap", "true", "false", "null", "undefined", "onclick", "type",
             "button", "aria", "label", "style", "key", "ref", "href", "src", "alt",
             # font-variation axes and theme words that sit next to the class name
             "opsz", "wght", "fill", "grad", "dark", "light", "normal", "inherit"}
    return sorted(n for n in names if n not in noise and "-" not in n)


def font_face_urls(css: str) -> list:
    return re.findall(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", css)


def localise(dashboard: str) -> None:
    fonts_dir = os.path.join(dashboard, "assets", "fonts")
    os.makedirs(fonts_dir, exist_ok=True)

    icons = icon_names(dashboard)
    print(f"icons found ({len(icons)}): {', '.join(icons)}")

    # Material Symbols, subset to exactly those ligatures
    ms_css = get("https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
                 ":opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
                 "&icon_names=" + ",".join(icons) + "&display=block").decode()
    ms_url = font_face_urls(ms_css)[0]
    ms_woff2 = get(ms_url)
    open(os.path.join(fonts_dir, "material-symbols-subset.woff2"), "wb").write(ms_woff2)

    # Inter, latin subset only (the dashboard is English)
    inter_css = get("https://fonts.googleapis.com/css2?family=Inter:wght@300..800&display=swap").decode()
    blocks = re.split(r"/\*\s*([a-z0-9-]+)\s*\*/", inter_css)
    latin = None
    for i in range(1, len(blocks) - 1, 2):
        if blocks[i] == "latin":
            latin = blocks[i + 1]
    if latin is None:
        raise SystemExit("could not find the latin subset in the Inter stylesheet")
    inter_url = font_face_urls(latin)[0]
    inter_range = re.search(r"unicode-range:\s*([^;]+);", latin).group(1).strip()
    inter_woff2 = get(inter_url)
    open(os.path.join(fonts_dir, "inter-latin.woff2"), "wb").write(inter_woff2)

    css = f"""/* Self-hosted dashboard fonts. Generated by tools/localise_dashboard_fonts.py
   Inter: latin subset. Material Symbols: subset to the {len(icons)} icons this app uses. */
@font-face {{
  font-family: 'Inter';
  font-style: normal;
  font-weight: 300 800;
  font-display: swap;
  src: url(./inter-latin.woff2) format('woff2');
  unicode-range: {inter_range};
}}
@font-face {{
  font-family: 'Material Symbols Outlined';
  font-style: normal;
  font-weight: 100 700;
  font-display: block;
  src: url(./material-symbols-subset.woff2) format('woff2');
}}
.material-symbols-outlined {{
  font-family: 'Material Symbols Outlined';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}}
"""
    open(os.path.join(fonts_dir, "fonts.css"), "w", encoding="utf-8").write(css)

    # Point index.html at the local copies
    index = os.path.join(dashboard, "index.html")
    html = open(index, encoding="utf-8").read()
    html = re.sub(r'\s*<link[^>]*fonts\.(?:googleapis|gstatic)\.com[^>]*>', "", html)
    marker = '    <link rel="stylesheet" crossorigin href='
    local = ('    <link rel="preload" href="./assets/fonts/inter-latin.woff2" as="font" '
             'type="font/woff2" crossorigin />\n'
             '    <link rel="stylesheet" href="./assets/fonts/fonts.css" />\n')
    if "assets/fonts/fonts.css" not in html:
        assert marker in html, "could not find the stylesheet link in dashboard/index.html"
        html = html.replace(marker, local + marker, 1)
    open(index, "w", encoding="utf-8").write(html)

    ms_kb = len(ms_woff2) // 1024
    inter_kb = len(inter_woff2) // 1024
    print(f"material-symbols-subset.woff2  {ms_kb} KB")
    print(f"inter-latin.woff2              {inter_kb} KB")
    print("dashboard/index.html now loads fonts locally")


if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    localise(sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, "dashboard"))
